catalogs:
  main:
    name: starscream
    storage_isolation: isolate
    force_destroy: true
    permissions: []
  kepler:
    name: kepler
    storage_isolation: isolate
    force_destroy: true
    permissions: []

schemas:
  main:
    catalog_name: kepler
    storage_isolation: default
    force_destroy: true
    permissions: []
  stars:
    catalog_name: kepler
    storage_isolation: isolate
    force_destroy: true
    permissions: []
