storages:
  starscream:
    force_destroy: true
  kepler:
    force_destroy: true

catalogs:
  main:
    name: starscream
    storage: starscream
    force_destroy: true
    permissions: []
  kepler:
    name: kepler
    storage: kepler
    force_destroy: true
    permissions: []

schemas:
  main:
    catalog_name: kepler
    force_destroy: true
    permissions: []
  stars:
    catalog_name: kepler
    force_destroy: true
    permissions: []
