storages:
  voyager:
    force_destroy: true
  triangulum:
    force_destroy: true

catalogs:
  main:
    name: voyager
    force_destroy: true
    storage: voyager
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
  triangulum:
    name: triangulum
    force_destroy: true
    storage: triangulum
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]

schemas:
  main:
    catalog_name: triangulum
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
  stars:
    catalog_name: triangulum
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]

volumes:
  cloudwatch:
    catalog_name: triangulum
    schema_name: main
    force_destroy: true
    permissions:
      - group: one-env-laboratory-sudoers
        privileges: [ALL_PRIVILEGES]
